# Dependencies
markdown:         kramdown
highlighter:      rouge

# Plugins
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            David Cook
tagline:          ''
description:      'Lead Consultant at Readify'
url:              http://davidcook.me
baseurl:          http://davidcook.me/

author:
  name:           'David Cook'
  url:            https://twitter.com/David_Cook

# Pagination
paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/poole/hyde

